import {JSDOM} from 'jsdom';
import {readFileSync} from 'node:fs';
import {createDatabase,seedStudent,seedLog,d1Database} from './helpers/database.mjs';
import {handleMaktabRegister,handleAttendancePage} from '../worker/src/maktabAttendance.js';
const read=f=>readFileSync(new URL('../'+f,import.meta.url),'utf8');
let pass=0,fail=0;
const check=(name,ok)=>{if(ok)pass++;else{fail++;console.log('FAIL:',name);}};
const db=createDatabase();
const dom=new JSDOM(read('index.html'),{runScripts:'outside-only',url:'https://test.local'}),w=dom.window;
try{
 seedStudent(db,'T',{role:'teacher'});seedStudent(db,'A',{name:'Alpha'});seedStudent(db,'Z',{name:'Zara'});
 db.exec("UPDATE maktab_settings SET maktab_day_min=1, timezone='UTC'; INSERT INTO maktab_terms (name,term_from,term_to) VALUES ('First','2026-08-01','2026-08-31'),('Second','2026-09-01','2026-09-30');");
 for(const date of ['2026-08-31','2026-09-01','2026-09-02'])seedLog(db,'Z',date);
 seedLog(db,'A','2026-09-02');
 const env={DB:d1Database(db)},auth={id:'T',role:'teacher'};
 const run=(query,who=auth)=>handleMaktabRegister({url:'https://x/maktab/attendance-register?'+query},env,who);
 for(const query of ['from=2026-09-01','from=2026-02-30&to=2026-03-03','from=2026-09-04&to=2026-09-01','from=2020-01-01&to=2026-09-01'])check('invalid range rejected: '+query,(await run(query)).status===400);
 check('student cannot read report',(await run('from=2026-09-01&to=2026-09-02',{id:'A',role:'student'})).status===403);
 const data=(await run('from=2026-08-31&to=2026-09-02')).data;
 check('custom range crosses terms without clipping',data.from==='2026-08-31' && data.to==='2026-09-02' && data.term_id===null && data.weeks.flatMap(x=>x.columns).length===3);
 const page=(await handleAttendancePage({url:'https://x/attendance/page?student_id=A&from=2026-08-31&to=2026-09-02'},env,auth)).data;
 check('report retains individual attendance percentage calculation',data.students.find(s=>s.id==='A').attendance_percent===page.percent);
 check('default register term selection unchanged',!!(await run('')).data.term_id);
 w.iconHtml=()=>'';w.maktabTodayISO=()=> '2026-09-24';
 w.eval(read('js/maktabAttendancePage.js'));w.eval(read('js/maktabDailyReport.js'));w.eval(read('js/maktabAttendanceReport.js'));
 check('week to date starts Monday',w.mkAttendanceReportPreset('week','2026-09-27').from==='2026-09-21');
 check('month to date starts first',w.mkAttendanceReportPreset('month','2026-09-24').from==='2026-09-01');
 check('alphabetical order',w.mkAttendanceReportRows(data,'name')[0].id==='A');
 check('attendance order uses active days first',w.mkAttendanceReportRows(data,'attendance')[0].id==='Z');
 check('Haidh marks stay distinct',w.mkAttendanceReportMark({cells:{d:'haidh'}},{date:'d'}).text==='H' && w.mkAttendanceReportMark({cells:{d:'predicted-haidh'}},{date:'d'}).text==='h');
 const weeks=Array.from({length:9},(_,i)=>{const d=new Date('2026-07-06T00:00:00Z');d.setUTCDate(d.getUTCDate()+i*7);return {monday:d.toISOString().slice(0,10),columns:[]};});
 const big={...data,from:'2026-07-06',to:'2026-09-06',teaching_days:['mon','tue','wed','thu'],weeks,students:Array.from({length:41},(_,i)=>({id:String(i),name:'Student '+i,cells:{}}))};
 const pages=w.mkAttendanceReportPages(big,'name');
 const pngPages=w.mkAttendanceReportPages(big,'name',Infinity);
 check('each PNG includes all students in order',pngPages.length===3 && pngPages.every(p=>p.students.length===41 && p.students.map(s=>s.id).join(',')===w.mkAttendanceReportRows(big,'name').map(s=>s.id).join(',')));
 check('one week group shares all students in one image',w.mkAttendanceReportPages({...big,weeks:weeks.slice(0,4)},'name',Infinity).length===1);
 check('four whole Maktab weeks per horizontal page',pages.length===9 && pages[0].weeks.length===4 && pages.every(p=>p.columns.length<=21) && pages.reduce((n,p)=>n+p.students.length*p.columns.length,0)===41*36);
 check('seven-day schedules never exceed 21 columns',w.mkAttendanceReportPages({...big,teaching_days:['mon','tue','wed','thu','fri','sat','sun']},'name').every(p=>p.columns.length<=21));
 check('partial weeks are padded without recording out-of-range activity',w.mkAttendanceReportWeeks({...data,from:'2026-09-01',to:'2026-09-02'})[0].columns[0].outside===true);
 check('Haidh suppresses period percent, including predicted marks',w.mkAttendanceReportPercent({attendance_percent:100,cells:{'2026-09-01':'haidh'}},data)==='' && w.mkAttendanceReportPercent({attendance_percent:100,cells:{'2026-09-01':'predicted-haidh'}},data)==='');
 check('Haidh outside the period does not suppress percent',w.mkAttendanceReportPercent({attendance_percent:80,cells:{'2020-01-01':'haidh'}},data)==='80%');
 check('week label uses day and month only',w.mkAttendanceReportWeekLabel('2026-09-21')==='21 Sept' || w.mkAttendanceReportWeekLabel('2026-09-21')==='21 Sep');
 const painted=[];
 w.HTMLCanvasElement.prototype.getContext=()=>({font:'',measureText:text=>({width:String(text).length*8}),fillRect(){},strokeRect(){},moveTo(){},lineTo(){},stroke(){},save(){},beginPath(){},rect(){},clip(){},restore(){},fillText:text=>painted.push(String(text))});
 const image=w.mkAttendanceReportCanvas(data,w.mkAttendanceReportPages(data,'name')[0],0,1);
 check('image draws report names, dates and attendance marks',image.width>0 && painted.includes('Alpha') && painted.includes('Zara') && painted.includes('✓'));
 // Fake only canvas/browser output, leaving the report DOM and handlers real.
 let drawn=0;w.mkAttendanceReportCanvas=()=>{drawn++;return {width:100,height:100,toDataURL:()=> 'data:image/jpeg;base64,/9j/2Q=='};};w.maktabDailyReportCanvasBlob=async()=>new w.Blob(['image'],{type:'image/png'});
 w.apiGetMaktabAttendanceReport=async(from,to)=>({...data,from,to});
 w.maktabOpenAttendanceReport();await new Promise(r=>setTimeout(r,25));
 check('report opens with date controls and populated grid',!!w.document.getElementById('marFrom') && w.document.querySelectorAll('.attendance-report-table tbody tr').length===2);
 check('share enabled only after images ready',drawn>0 && !w.document.getElementById('marShare').disabled);
 let shared=0;w.navigator.share=async({files})=>{shared=files.length;check('share uses PNG images',files.every(f=>f.type==='image/png' && f.name.endsWith('.png')));};await w.mkAttendanceReportShare();check('native share receives one report file',shared===1);
 let downloads=0;w.navigator.canShare=()=>false;w.maktabDailyReportDownload=(file)=>{downloads++;check('download remains PDF',file.type==='application/pdf');};await w.mkAttendanceReportShare();check('unsupported sharing explains PDF option without multiple downloads',downloads===0 && w.document.getElementById('marStatus').textContent.includes('Download PDF'));
 w.navigator.canShare=()=>true;
 w.document.getElementById('marDownload').click();
 check('explicit download saves a PDF even with native sharing available',downloads===1 && !w.document.getElementById('marDownload').disabled);
 const pdf=w.mkAttendanceReportPdf([{width:100,height:100,bytes:new w.Uint8Array([255,216,255,217])}]);
 const pdfText=await new Promise(resolve=>{const reader=new w.FileReader();reader.onload=()=>resolve(reader.result);reader.readAsText(pdf);});
 check('PDF uses portrait A4 pages',pdfText.includes('/MediaBox [0 0 595 842]'));
 check('requested explanatory text and duplicate date heading removed',!w.document.querySelector('#marPreview h3') && !w.document.getElementById('maktabAttendanceReport').textContent.includes('Date ranges may span') && w.document.getElementById('marStatus').textContent==='');
 w.apiGetMaktabAttendanceReport=async()=>({...big,weeks:w.mkAttendanceReportWeeks(big)});
 w.document.getElementById('marFrom').value=big.from;w.document.getElementById('marTo').value=big.to;
 w.document.getElementById('marFrom').dispatchEvent(new w.Event('change'));await new Promise(r=>setTimeout(r,80));
 await w.mkAttendanceReportShare();check('PNG sharing uses one image per week group, without row pagination',shared===3);
 w.apiGetMaktabAttendanceReport=async(from,to)=>({...data,from,to});
 w.document.getElementById('marFrom').dispatchEvent(new w.Event('change'));await new Promise(r=>setTimeout(r,25));
 const sort=w.document.getElementById('marSort');sort.value='attendance';sort.dispatchEvent(new w.Event('change'));await new Promise(r=>setTimeout(r,25));
 check('changing sort reorders visible report',w.document.querySelector('.attendance-report-table tbody th').textContent==='Zara');
 let release;w.apiGetMaktabAttendanceReport=()=>new Promise(resolve=>{release=resolve;});
 const from=w.document.getElementById('marFrom');from.value='2026-09-01';from.dispatchEvent(new w.Event('change'));
 check('changing dates disables stale exports',w.document.getElementById('marShare').disabled && w.document.getElementById('marDownload').disabled);
 w.document.getElementById('marClose').click();release({...data,from:'2026-09-01',to:'2026-09-24'});await new Promise(r=>setTimeout(r,25));
 check('late request cannot reopen closed report',!w.document.getElementById('maktabAttendanceReport'));
}catch(e){fail++;console.log('FAIL:',e.stack);}finally{db.close();w.close();}
console.log(`${pass} passed, ${fail} failed`);process.exitCode=fail?1:0;
