import {JSDOM} from 'jsdom';
import {readFileSync} from 'node:fs';
import {createDatabase,seedStudent,seedLog,d1Database} from './helpers/database.mjs';
import {handleMaktabRegister,handleAttendancePage} from '../worker/src/maktabAttendance.js';
const read=f=>readFileSync(new URL('../'+f,import.meta.url),'utf8');
let pass=0,fail=0;
const check=(name,ok)=>{if(ok)pass++;else{fail++;console.log('FAIL:',name);}};
const db=createDatabase();
const dom=new JSDOM(read('index.html'),{runScripts:'outside-only',url:'https://test.local'}),w=dom.window;
try{
 seedStudent(db,'T',{role:'teacher'});seedStudent(db,'A',{name:'Alpha'});seedStudent(db,'Z',{name:'Zara'});
 db.exec("UPDATE maktab_settings SET maktab_day_min=1, timezone='UTC'; INSERT INTO maktab_terms (name,term_from,term_to) VALUES ('First','2026-08-01','2026-08-31'),('Second','2026-09-01','2026-09-30');");
 for(const date of ['2026-08-31','2026-09-01','2026-09-02'])seedLog(db,'Z',date);
 seedLog(db,'A','2026-09-02');
 const env={DB:d1Database(db)},auth={id:'T',role:'teacher'};
 const run=(query,who=auth)=>handleMaktabRegister({url:'https://x/maktab/attendance-register?'+query},env,who);
 for(const query of ['from=2026-09-01','from=2026-02-30&to=2026-03-03','from=2026-09-04&to=2026-09-01','from=2020-01-01&to=2026-09-01'])check('invalid range rejected: '+query,(await run(query)).status===400);
 check('student cannot read report',(await run('from=2026-09-01&to=2026-09-02',{id:'A',role:'student'})).status===403);
 const data=(await run('from=2026-08-31&to=2026-09-02')).data;
 check('custom range crosses terms without clipping',data.from==='2026-08-31' && data.to==='2026-09-02' && data.term_id===null && data.weeks.flatMap(x=>x.columns).length===3);
 const page=(await handleAttendancePage({url:'https://x/attendance/page?student_id=A&from=2026-08-31&to=2026-09-02'},env,auth)).data;
 check('report retains individual attendance percentage calculation',data.students.find(s=>s.id==='A').attendance_percent===page.percent);
 check('default register term selection unchanged',!!(await run('')).data.term_id);
 w.iconHtml=()=>'';w.maktabTodayISO=()=> '2026-09-24';
 w.eval(read('js/maktabAttendancePage.js'));w.eval(read('js/maktabDailyReport.js'));w.eval(read('js/maktabAttendanceReport.js'));
 check('week to date starts Monday',w.mkAttendanceReportPreset('week','2026-09-27').from==='2026-09-21');
 check('month to date starts first',w.mkAttendanceReportPreset('month','2026-09-24').from==='2026-09-01');
 check('alphabetical order',w.mkAttendanceReportRows(data,'name')[0].id==='A');
 check('attendance order uses active days first',w.mkAttendanceReportRows(data,'attendance')[0].id==='Z');
 check('Haidh marks stay distinct',w.mkAttendanceReportMark({cells:{d:'haidh'}},{date:'d'}).text==='H' && w.mkAttendanceReportMark({cells:{d:'predicted-haidh'}},{date:'d'}).text==='h');
 const big={...data,weeks:[{columns:Array.from({length:41},(_,i)=>({date:'d'+i}))}],students:Array.from({length:61},(_,i)=>({id:String(i),name:'Student '+i,cells:{}}))};
 const pages=w.mkAttendanceReportPages(big,'name');
 check('long reports paginate without losing cells',pages.length===9 && pages.reduce((n,p)=>n+p.students.length*p.columns.length,0)===61*41);
 const painted=[];
 w.HTMLCanvasElement.prototype.getContext=()=>({font:'',measureText:text=>({width:String(text).length*8}),fillRect(){},strokeRect(){},save(){},beginPath(){},rect(){},clip(){},restore(){},fillText:text=>painted.push(String(text))});
 const image=w.mkAttendanceReportCanvas(data,w.mkAttendanceReportPages(data,'name')[0],0,1);
 check('image draws report names, dates and attendance marks',image.width>0 && painted.includes('Alpha') && painted.includes('Zara') && painted.includes('✓'));
 // Fake only canvas/browser output, leaving the report DOM and handlers real.
 let drawn=0;w.mkAttendanceReportCanvas=()=>{drawn++;return {};};w.maktabDailyReportCanvasBlob=async()=>new w.Blob(['image'],{type:'image/png'});
 w.apiGetMaktabAttendanceReport=async(from,to)=>({...data,from,to});
 w.maktabOpenAttendanceReport();await new Promise(r=>setTimeout(r,0));
 check('report opens with date controls and populated grid',!!w.document.getElementById('marFrom') && w.document.querySelectorAll('.attendance-report-table tbody tr').length===2);
 check('share enabled only after images ready',drawn>0 && !w.document.getElementById('marShare').disabled);
 let shared=0;w.navigator.share=async({files})=>{shared=files.length;};await w.mkAttendanceReportShare();check('native share receives image file',shared===1);
 let downloads=0;w.navigator.canShare=()=>false;w.maktabDailyReportDownload=()=>{downloads++;};await w.mkAttendanceReportShare();check('unsupported sharing downloads the image',downloads===1);
 const sort=w.document.getElementById('marSort');sort.value='attendance';sort.dispatchEvent(new w.Event('change'));await new Promise(r=>setTimeout(r,0));
 check('changing sort reorders visible report',w.document.querySelector('.attendance-report-table tbody th').textContent==='Zara');
 let release;w.apiGetMaktabAttendanceReport=()=>new Promise(resolve=>{release=resolve;});
 const from=w.document.getElementById('marFrom');from.value='2026-09-01';from.dispatchEvent(new w.Event('change'));
 check('changing dates disables stale export',w.document.getElementById('marShare').disabled);
 w.document.getElementById('marClose').click();release({...data,from:'2026-09-01',to:'2026-09-24'});await new Promise(r=>setTimeout(r,0));
 check('late request cannot reopen closed report',!w.document.getElementById('maktabAttendanceReport'));
}catch(e){fail++;console.log('FAIL:',e.stack);}finally{db.close();w.close();}
console.log(`${pass} passed, ${fail} failed`);process.exitCode=fail?1:0;
